name: CI/CD for Diabetes Prediction Web App (with Render Deployment)

on:
  push:
    branches: [ main ]

jobs:
  train_model:
    name: Train Model and Save PKL (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model and save PKL
        run: python dia_ml.py  
      - name: Commit & push updated PKL
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add diabetes_model.pkl
          git commit -m "Auto-update diabetes_model.pkl"
          git push
        continue-on-error: true

  docker_test:
    name: Build & Test Docker Image
    needs: train_model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t diabetes-flask-app .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name diabetes-app diabetes-flask-app

      - name: Wait for app to start
        run: sleep 10

      - name: Test app
        run: curl -f http://localhost:5000 || exit 1

      - name: Stop & Remove container
        run: |
          docker stop diabetes-app
          docker rm diabetes-app

  deploy_to_render:
    name: Deploy to Render
    needs: docker_test
    runs-on: ubuntu-latest
    permissions:
      deployments: write

    steps:
      - name: Deploy to Render service
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
